In [ ]:
#Un DataFrame tiene 
#Cada una de las columnas de un dataframe es una serie

#Para concatenar hay que hacerlo a través del axis= 1

In [4]:
#Para acceder mediante loc como de DataFrame, aunque solo se vaya a coger una columna, hay que poner 2 puntos

In [8]:
import requests
import json
import pandas as pd

In [12]:
r = requests.get(url='http://data.nba.net/prod/v2/2018/teams.json')
json_readed = json.loads(r.text)

In [15]:
df_json = pd.DataFrame(json_readed)
df_json

,_internal,league
pubDateTime,2018-08-30 20:00:04.422,NaN
xslt,xsl/league/roster/marty_teams_list.xsl,NaN
eventName,league_roster,NaN
standard,NaN,"[{'isNBAFranchise': False, 'isAllStar': True, ..."
africa,NaN,"[{'isNBAFranchise': False, 'isAllStar': False,..."
sacramento,NaN,"[{'isNBAFranchise': True, 'isAllStar': False, ..."
vegas,NaN,"[{'isNBAFranchise': True, 'isAllStar': False, ..."
utah,NaN,"[{'isNBAFranchise': True, 'isAllStar': False, ..."

In [18]:
df2 = df_json.loc['standard':, 'league':'league'] #De este modo se accede como Dataframe a partir de una fila y una columna en concreto. Si hubiese más columnas a la derecha de league y dejase solo los dos puntos, se seleccionarúan todas a partir de ella

                                                       league
standard    [{'isNBAFranchise': False, 'isAllStar': True, ...
africa      [{'isNBAFranchise': False, 'isAllStar': False,...
sacramento  [{'isNBAFranchise': True, 'isAllStar': False, ...
vegas       [{'isNBAFranchise': True, 'isAllStar': False, ...
utah        [{'isNBAFranchise': True, 'isAllStar': False, ...

## Esto es lo mismo

In [34]:
#Pasar una serie a DataFrame:
df2_serie = df_json.loc['standard':, 'league']
print(type(df2_serie))

df2_serie_a_dataframe = pd.DataFrame(df2_serie)
print(type(df2_serie_a_dataframe))
df2_serie_a_dataframe

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

                                                       league
standard    [{'isNBAFranchise': False, 'isAllStar': True, ...
africa      [{'isNBAFranchise': False, 'isAllStar': False,...
sacramento  [{'isNBAFranchise': True, 'isAllStar': False, ...
vegas       [{'isNBAFranchise': True, 'isAllStar': False, ...
utah        [{'isNBAFranchise': True, 'isAllStar': False, ...

## Cómo acceder a los elementos de la lista

In [22]:
df2['league'][0] #En cada una de las posiciones tenemos una lista de jsons

[{'isNBAFranchise': False,
  'isAllStar': True,
  'city': 'USA',
  'altCityName': 'USA',
  'fullName': 'USA',
  'tricode': 'USA',
  'teamId': '1610616843',
  'nickname': 'USA',
  'urlName': 'usa',
  'confName': 'East',
  'divName': 'East'},
 {'isNBAFranchise': False,
  'isAllStar': True,
  'city': 'World',
  'altCityName': 'World',
  'fullName': 'World',
  'tricode': 'WLD',
  'teamId': '1610616844',
  'nickname': 'World',
  'urlName': 'world',
  'confName': 'East',
  'divName': 'East'},
 {'isNBAFranchise': False,
  'isAllStar': True,
  'city': 'Team',
  'altCityName': 'Team',
  'fullName': 'All-Stars',
  'tricode': 'EST',
  'teamId': '1699999999',
  'nickname': 'All-Stars',
  'urlName': 'assn_away',
  'confName': 'East',
  'divName': 'East'},
 {'isNBAFranchise': False,
  'isAllStar': True,
  'city': 'Team',
  'altCityName': 'Team',
  'fullName': 'All-Stars',
  'tricode': 'WST',
  'teamId': '1699999998',
  'nickname': 'All-Stars',
  'urlName': 'assn_home',
  'confName': 'West',
  'divName': 'West'},
 {'isNBAFranchise': False,
  'isAllStar': True,
  'city': 'Team Giannis',
  'altCityName': 'Team Giannis',
  'fullName': 'Team Giannis',
  'tricode': 'GNS',
  'teamId': '1610616833',
  'nickname': 'Team Giannis',
  'urlName': 'team_giannis',
  'confName': 'East',
  'divName': 'East'},
 {'isNBAFranchise': False,
  'isAllStar': True,
  'city': 'Team LeBron',
  'altCityName': 'Team LeBron',
  'fullName': 'Team LeBron',
  'tricode': 'LBN',
  'teamId': '1610616834',
  'nickname': 'Team LeBron',
  'urlName': 'team_lebron',
  'confName': 'West',
  'divName': 'West'},
 {'isNBAFranchise': False,
  'isAllStar': False,
  'city': 'Team',
  'altCityName': 'Team',
  'fullName': 'Team Africa',
  'tricode': 'AFR',
  'teamId': '12326',
  'nickname': 'Africa',
  'urlName': 'africa',
  'confName': '',
  'divName': ''},
 {'isNBAFranchise': False,
  'isAllStar': False,
  'city': 'Team',
  'altCityName': 'Team',
  'fullName': 'Team World',
  'tricode': 'WLD',
  'teamId': '12327',
  'nickname': 'World',
  'urlName': 'world',
  'confName': '',
  'divName': ''},
 {'isNBAFranchise': False,
  'isAllStar': False,
  'city': 'Adelaide',
  'altCityName': 'Adelaide',
  'fullName': 'Adelaide 36ers',
  'tricode': 'ADL',
  'teamId': '15019',
  'nickname': '36ers',
  'urlName': '36ers',
  'confName': 'Intl',
  'divName': ''},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Atlanta',
  'altCityName': 'Atlanta',
  'fullName': 'Atlanta Hawks',
  'tricode': 'ATL',
  'teamId': '1610612737',
  'nickname': 'Hawks',
  'urlName': 'hawks',
  'confName': 'East',
  'divName': 'Southeast'},
 {'isNBAFranchise': False,
  'isAllStar': False,
  'city': 'Beijing',
  'altCityName': 'Beijing',
  'fullName': 'Beijing Ducks',
  'tricode': 'BJD',
  'teamId': '15021',
  'nickname': 'Ducks',
  'urlName': 'ducks',
  'confName': 'Intl',
  'divName': ''},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Boston',
  'altCityName': 'Boston',
  'fullName': 'Boston Celtics',
  'tricode': 'BOS',
  'teamId': '1610612738',
  'nickname': 'Celtics',
  'urlName': 'celtics',
  'confName': 'East',
  'divName': 'Atlantic'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Brooklyn',
  'altCityName': 'Brooklyn',
  'fullName': 'Brooklyn Nets',
  'tricode': 'BKN',
  'teamId': '1610612751',
  'nickname': 'Nets',
  'urlName': 'nets',
  'confName': 'East',
  'divName': 'Atlantic'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Charlotte',
  'altCityName': 'Charlotte',
  'fullName': 'Charlotte Hornets',
  'tricode': 'CHA',
  'teamId': '1610612766',
  'nickname': 'Hornets',
  'urlName': 'hornets',
  'confName': 'East',
  'divName': 'Southeast'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Chicago',
  'altCityName': 'Chicago',
  'fullName': 'Chicago Bulls',
  'tricode': 'CHI',
  'teamId': '1610612741',
  'nickname': 'Bulls',
  'urlName': 'bulls',
  'confName': 'East',
  'divName': 'Central'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Cleveland',
  'altCityName': 'Cleveland',
  'fullName': 'Cleveland Cavaliers',
  'tricode': 'CLE',
  'teamId': '1610612739',
  'nickname': 'Cavaliers',
  'urlName': 'cavaliers',
  'confName': 'East',
  'divName': 'Central'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Dallas',
  'altCityName': 'Dallas',
  'fullName': 'Dallas Mavericks',
  'tricode': 'DAL',
  'teamId': '1610612742',
  'nickname': 'Mavericks',
  'urlName': 'mavericks',
  'confName': 'West',
  'divName': 'Southwest'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Denver',
  'altCityName': 'Denver',
  'fullName': 'Denver Nuggets',
  'tricode': 'DEN',
  'teamId': '1610612743',
  'nickname': 'Nuggets',
  'urlName': 'nuggets',
  'confName': 'West',
  'divName': 'Northwest'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Detroit',
  'altCityName': 'Detroit',
  'fullName': 'Detroit Pistons',
  'tricode': 'DET',
  'teamId': '1610612765',
  'nickname': 'Pistons',
  'urlName': 'pistons',
  'confName': 'East',
  'divName': 'Central'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Golden State',
  'altCityName': 'Golden State',
  'fullName': 'Golden State Warriors',
  'tricode': 'GSW',
  'teamId': '1610612744',
  'nickname': 'Warriors',
  'urlName': 'warriors',
  'confName': 'West',
  'divName': 'Pacific'},
 {'isNBAFranchise': False,
  'isAllStar': False,
  'city': 'Guangzhou',
  'altCityName': 'Guangzhou',
  'fullName': 'Guangzhou Long-Lions',
  'tricode': 'GUA',
  'teamId': '15018',
  'nickname': 'Long-Lions',
  'urlName': 'long-lions',
  'confName': 'Intl',
  'divName': ''},
 {'isNBAFranchise': False,
  'isAllStar': False,
  'city': 'Haifa',
  'altCityName': 'Haifa',
  'fullName': 'Maccabi Haifa',
  'tricode': 'MAC',
  'teamId': '93',
  'nickname': 'Maccabi Haifa',
  'urlName': 'maccabi_haifa',
  'confName': 'Intl',
  'divName': ''},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Houston',
  'altCityName': 'Houston',
  'fullName': 'Houston Rockets',
  'tricode': 'HOU',
  'teamId': '1610612745',
  'nickname': 'Rockets',
  'urlName': 'rockets',
  'confName': 'West',
  'divName': 'Southwest'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Indiana',
  'altCityName': 'Indiana',
  'fullName': 'Indiana Pacers',
  'tricode': 'IND',
  'teamId': '1610612754',
  'nickname': 'Pacers',
  'urlName': 'pacers',
  'confName': 'East',
  'divName': 'Central'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'LA',
  'altCityName': 'LA Clippers',
  'fullName': 'LA Clippers',
  'tricode': 'LAC',
  'teamId': '1610612746',
  'nickname': 'Clippers',
  'urlName': 'clippers',
  'confName': 'West',
  'divName': 'Pacific'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Los Angeles',
  'altCityName': 'Los Angeles Lakers',
  'fullName': 'Los Angeles Lakers',
  'tricode': 'LAL',
  'teamId': '1610612747',
  'nickname': 'Lakers',
  'urlName': 'lakers',
  'confName': 'West',
  'divName': 'Pacific'},
 {'isNBAFranchise': False,
  'isAllStar': False,
  'city': 'Melbourne',
  'altCityName': 'Melbourne',
  'fullName': 'Melbourne United',
  'tricode': 'MEL',
  'teamId': '15016',
  'nickname': 'United',
  'urlName': 'united',
  'confName': 'Intl',
  'divName': ''},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Memphis',
  'altCityName': 'Memphis',
  'fullName': 'Memphis Grizzlies',
  'tricode': 'MEM',
  'teamId': '1610612763',
  'nickname': 'Grizzlies',
  'urlName': 'grizzlies',
  'confName': 'West',
  'divName': 'Southwest'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Miami',
  'altCityName': 'Miami',
  'fullName': 'Miami Heat',
  'tricode': 'MIA',
  'teamId': '1610612748',
  'nickname': 'Heat',
  'urlName': 'heat',
  'confName': 'East',
  'divName': 'Southeast'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Milwaukee',
  'altCityName': 'Milwaukee',
  'fullName': 'Milwaukee Bucks',
  'tricode': 'MIL',
  'teamId': '1610612749',
  'nickname': 'Bucks',
  'urlName': 'bucks',
  'confName': 'East',
  'divName': 'Central'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Minnesota',
  'altCityName': 'Minnesota',
  'fullName': 'Minnesota Timberwolves',
  'tricode': 'MIN',
  'teamId': '1610612750',
  'nickname': 'Timberwolves',
  'urlName': 'timberwolves',
  'confName': 'West',
  'divName': 'Northwest'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'New Orleans',
  'altCityName': 'New Orleans',
  'fullName': 'New Orleans Pelicans',
  'tricode': 'NOP',
  'teamId': '1610612740',
  'nickname': 'Pelicans',
  'urlName': 'pelicans',
  'confName': 'West',
  'divName': 'Southwest'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'New York',
  'altCityName': 'New York',
  'fullName': 'New York Knicks',
  'tricode': 'NYK',
  'teamId': '1610612752',
  'nickname': 'Knicks',
  'urlName': 'knicks',
  'confName': 'East',
  'divName': 'Atlantic'},
 {'isNBAFranchise': False,
  'isAllStar': False,
  'city': 'New Zealand',
  'altCityName': 'New Zealand',
  'fullName': 'New Zealand Breakers',
  'tricode': 'NZB',
  'teamId': '15020',
  'nickname': 'Breakers',
  'urlName': 'breakers',
  'confName': 'Intl',
  'divName': ''},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Oklahoma City',
  'altCityName': 'Oklahoma City',
  'fullName': 'Oklahoma City Thunder',
  'tricode': 'OKC',
  'teamId': '1610612760',
  'nickname': 'Thunder',
  'urlName': 'thunder',
  'confName': 'West',
  'divName': 'Northwest'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Orlando',
  'altCityName': 'Orlando',
  'fullName': 'Orlando Magic',
  'tricode': 'ORL',
  'teamId': '1610612753',
  'nickname': 'Magic',
  'urlName': 'magic',
  'confName': 'East',
  'divName': 'Southeast'},
 {'isNBAFranchise': False,
  'isAllStar': False,
  'city': 'Perth',
  'altCityName': 'Perth',
  'fullName': 'Perth Wildcats',
  'tricode': 'PER',
  'teamId': '104',
  'nickname': 'Wildcats',
  'urlName': 'wildcats',
  'confName': 'Intl',
  'divName': ''},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Philadelphia',
  'altCityName': 'Philadelphia',
  'fullName': 'Philadelphia 76ers',
  'tricode': 'PHI',
  'teamId': '1610612755',
  'nickname': '76ers',
  'urlName': 'sixers',
  'confName': 'East',
  'divName': 'Atlantic'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Phoenix',
  'altCityName': 'Phoenix',
  'fullName': 'Phoenix Suns',
  'tricode': 'PHX',
  'teamId': '1610612756',
  'nickname': 'Suns',
  'urlName': 'suns',
  'confName': 'West',
  'divName': 'Pacific'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Portland',
  'altCityName': 'Portland',
  'fullName': 'Portland Trail Blazers',
  'tricode': 'POR',
  'teamId': '1610612757',
  'nickname': 'Trail Blazers',
  'urlName': 'blazers',
  'confName': 'West',
  'divName': 'Northwest'},
 {'isNBAFranchise': False,
  'isAllStar': False,
  'city': 'Rio de Janeiro',
  'altCityName': 'Rio de Janeiro',
  'fullName': 'Rio de Janeiro Flamengo',
  'tricode': 'FLA',
  'teamId': '12325',
  'nickname': 'Flamengo',
  'urlName': 'flamengo',
  'confName': 'Intl',
  'divName': ''},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Sacramento',
  'altCityName': 'Sacramento',
  'fullName': 'Sacramento Kings',
  'tricode': 'SAC',
  'teamId': '1610612758',
  'nickname': 'Kings',
  'urlName': 'kings',
  'confName': 'West',
  'divName': 'Pacific'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'San Antonio',
  'altCityName': 'San Antonio',
  'fullName': 'San Antonio Spurs',
  'tricode': 'SAS',
  'teamId': '1610612759',
  'nickname': 'Spurs',
  'urlName': 'spurs',
  'confName': 'West',
  'divName': 'Southwest'},
 {'isNBAFranchise': False,
  'isAllStar': False,
  'city': 'Shanghai',
  'altCityName': 'Shanghai',
  'fullName': 'Shanghai Sharks',
  'tricode': 'SDS',
  'teamId': '12329',
  'nickname': 'Shanghai Sharks',
  'urlName': 'shanghai_sharks',
  'confName': 'Intl',
  'divName': ''},
 {'isNBAFranchise': False,
  'isAllStar': False,
  'city': 'Sydney',
  'altCityName': 'Sydney',
  'fullName': 'Sydney Kings',
  'tricode': 'SYD',
  'teamId': '15015',
  'nickname': 'Kings',
  'urlName': 'kings',
  'confName': 'Intl',
  'divName': ''},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Toronto',
  'altCityName': 'Toronto',
  'fullName': 'Toronto Raptors',
  'tricode': 'TOR',
  'teamId': '1610612761',
  'nickname': 'Raptors',
  'urlName': 'raptors',
  'confName': 'East',
  'divName': 'Atlantic'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Utah',
  'altCityName': 'Utah',
  'fullName': 'Utah Jazz',
  'tricode': 'UTA',
  'teamId': '1610612762',
  'nickname': 'Jazz',
  'urlName': 'jazz',
  'confName': 'West',
  'divName': 'Northwest'},
 {'isNBAFranchise': True,
  'isAllStar': False,
  'city': 'Washington',
  'altCityName': 'Washington',
  'fullName': 'Washington Wizards',
  'tricode': 'WAS',
  'teamId': '1610612764',
  'nickname': 'Wizards',
  'urlName': 'wizards',
  'confName': 'East',
  'divName': 'Southeast'}]

In [24]:
for i, x in enumerate(df2['league']):
    with open(str(i) + '.json', 'w+') as outfile:
        json.dump(x, outfile, indent=4)

In [35]:
len(df2)

5

In [30]:
df_final = None

for i in range(len(df2)): #De esta forma se leerían todos los json de forma consecutiva
    new_df = pd.read_json(str(i)+'.json')
    if i == 0: #es la primera iteración
        df_league_json = new_df
    else:
        df_final = pd.concat([df_final, new_df], axis = 0) #Así se concatena por abajo


df_final.head(3)

,isNBAFranchise,isAllStar,city,altCityName,fullName,tricode,teamId,nickname,urlName,confName,divName
0,False,False,Team,Team,Team Africa,AFR,12326,Africa,africa,,
1,False,False,Team,Team,Team World,WLD,12327,World,world,,
0,True,False,Golden State,Golden State,Golden State Warriors,GSW,1610612744,Warriors,warriors,Sacramento,

In [31]:

df_definitivo = None

for i, c in enumerate(df2['league']):
    if i == 0:
        df_definitivo = pd.DataFrame(c)
    else:
        df_definitivo = pd.concat([df_definitivo, pd.DataFrame(c)], axis=0)
    
df_definitivo

,isNBAFranchise,isAllStar,city,altCityName,fullName,tricode,teamId,nickname,urlName,confName,divName
0,False,True,USA,USA,USA,USA,1610616843,USA,usa,East,East
1,False,True,World,World,World,WLD,1610616844,World,world,East,East
2,False,True,Team,Team,All-Stars,EST,1699999999,All-Stars,assn_away,East,East
3,False,True,Team,Team,All-Stars,WST,1699999998,All-Stars,assn_home,West,West
4,False,True,Team Giannis,Team Giannis,Team Giannis,GNS,1610616833,Team Giannis,team_giannis,East,East
...,...,...,...,...,...,...,...,...,...,...,...
29,True,False,Washington,Washington,Washington Wizards,WAS,1610612764,Wizards,wizards,summer,
0,True,False,Atlanta,Atlanta,Atlanta Hawks,ATL,1610612737,Hawks,hawks,Utah,
1,True,False,Memphis,Memphis,Memphis Grizzlies,MEM,1610612763,Grizzlies,grizzlies,Utah,
2,True,False,San Antonio,San Antonio,San Antonio Spurs,SAS,1610612759,Spurs,spurs,Utah,
3,True,False,Utah,Utah,Utah Jazz,UTA,1610612762,Jazz,jazz,Utah,